repos:
-   repo: https://github.com/pycqa/isort
    rev: 5.7.0
    hooks:
    - id: isort
-   repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
    - id: black
      args: [--config=.pyproject.toml, --target-version=py37]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: flake8
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.812
    hooks:
    - id: mypy
      args: [--disallow-untyped-defs, --ignore-missing-imports]
      exclude: src/models/smp
